/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EntropyPublicDecryptionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "entropyOracle"
      | "entropyRequests"
      | "getEncryptedValue"
      | "getEntropyOracle"
      | "isInitialized"
      | "requestEntropy"
      | "storeAndMakePublic"
      | "storeAndMakePublicWithEntropy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EntropyRequested"
      | "ValueMadePubliclyDecryptable"
      | "ValueStored"
      | "ValueStoredWithEntropy"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestEntropy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeAndMakePublic",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeAndMakePublicWithEntropy",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeAndMakePublic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeAndMakePublicWithEntropy",
    data: BytesLike
  ): Result;
}

export namespace EntropyRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, caller: AddressLike];
  export type OutputTuple = [requestId: bigint, caller: string];
  export interface OutputObject {
    requestId: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueMadePubliclyDecryptableEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueStoredEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueStoredWithEntropyEvent {
  export type InputTuple = [requestId: BigNumberish, user: AddressLike];
  export type OutputTuple = [requestId: bigint, user: string];
  export interface OutputObject {
    requestId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropyPublicDecryption extends BaseContract {
  connect(runner?: ContractRunner | null): EntropyPublicDecryption;
  waitForDeployment(): Promise<this>;

  interface: EntropyPublicDecryptionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  entropyRequests: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getEncryptedValue: TypedContractMethod<[], [string], "view">;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  requestEntropy: TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  storeAndMakePublic: TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  storeAndMakePublicWithEntropy: TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike, requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "entropyRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getEncryptedValue"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "requestEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "storeAndMakePublic"
  ): TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storeAndMakePublicWithEntropy"
  ): TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike, requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EntropyRequested"
  ): TypedContractEvent<
    EntropyRequestedEvent.InputTuple,
    EntropyRequestedEvent.OutputTuple,
    EntropyRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ValueMadePubliclyDecryptable"
  ): TypedContractEvent<
    ValueMadePubliclyDecryptableEvent.InputTuple,
    ValueMadePubliclyDecryptableEvent.OutputTuple,
    ValueMadePubliclyDecryptableEvent.OutputObject
  >;
  getEvent(
    key: "ValueStored"
  ): TypedContractEvent<
    ValueStoredEvent.InputTuple,
    ValueStoredEvent.OutputTuple,
    ValueStoredEvent.OutputObject
  >;
  getEvent(
    key: "ValueStoredWithEntropy"
  ): TypedContractEvent<
    ValueStoredWithEntropyEvent.InputTuple,
    ValueStoredWithEntropyEvent.OutputTuple,
    ValueStoredWithEntropyEvent.OutputObject
  >;

  filters: {
    "EntropyRequested(uint256,address)": TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;
    EntropyRequested: TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;

    "ValueMadePubliclyDecryptable()": TypedContractEvent<
      ValueMadePubliclyDecryptableEvent.InputTuple,
      ValueMadePubliclyDecryptableEvent.OutputTuple,
      ValueMadePubliclyDecryptableEvent.OutputObject
    >;
    ValueMadePubliclyDecryptable: TypedContractEvent<
      ValueMadePubliclyDecryptableEvent.InputTuple,
      ValueMadePubliclyDecryptableEvent.OutputTuple,
      ValueMadePubliclyDecryptableEvent.OutputObject
    >;

    "ValueStored(address)": TypedContractEvent<
      ValueStoredEvent.InputTuple,
      ValueStoredEvent.OutputTuple,
      ValueStoredEvent.OutputObject
    >;
    ValueStored: TypedContractEvent<
      ValueStoredEvent.InputTuple,
      ValueStoredEvent.OutputTuple,
      ValueStoredEvent.OutputObject
    >;

    "ValueStoredWithEntropy(uint256,address)": TypedContractEvent<
      ValueStoredWithEntropyEvent.InputTuple,
      ValueStoredWithEntropyEvent.OutputTuple,
      ValueStoredWithEntropyEvent.OutputObject
    >;
    ValueStoredWithEntropy: TypedContractEvent<
      ValueStoredWithEntropyEvent.InputTuple,
      ValueStoredWithEntropyEvent.OutputTuple,
      ValueStoredWithEntropyEvent.OutputObject
    >;
  };
}
