/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PublicDecryptSingleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getEncryptedValue"
      | "isInitialized"
      | "storeAndMakePublic"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ValueMadePubliclyDecryptable" | "ValueStored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "storeAndMakePublic",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeAndMakePublic",
    data: BytesLike
  ): Result;
}

export namespace ValueMadePubliclyDecryptableEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueStoredEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PublicDecryptSingle extends BaseContract {
  connect(runner?: ContractRunner | null): PublicDecryptSingle;
  waitForDeployment(): Promise<this>;

  interface: PublicDecryptSingleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getEncryptedValue: TypedContractMethod<[], [string], "view">;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  storeAndMakePublic: TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedValue"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "storeAndMakePublic"
  ): TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ValueMadePubliclyDecryptable"
  ): TypedContractEvent<
    ValueMadePubliclyDecryptableEvent.InputTuple,
    ValueMadePubliclyDecryptableEvent.OutputTuple,
    ValueMadePubliclyDecryptableEvent.OutputObject
  >;
  getEvent(
    key: "ValueStored"
  ): TypedContractEvent<
    ValueStoredEvent.InputTuple,
    ValueStoredEvent.OutputTuple,
    ValueStoredEvent.OutputObject
  >;

  filters: {
    "ValueMadePubliclyDecryptable()": TypedContractEvent<
      ValueMadePubliclyDecryptableEvent.InputTuple,
      ValueMadePubliclyDecryptableEvent.OutputTuple,
      ValueMadePubliclyDecryptableEvent.OutputObject
    >;
    ValueMadePubliclyDecryptable: TypedContractEvent<
      ValueMadePubliclyDecryptableEvent.InputTuple,
      ValueMadePubliclyDecryptableEvent.OutputTuple,
      ValueMadePubliclyDecryptableEvent.OutputObject
    >;

    "ValueStored(address)": TypedContractEvent<
      ValueStoredEvent.InputTuple,
      ValueStoredEvent.OutputTuple,
      ValueStoredEvent.OutputObject
    >;
    ValueStored: TypedContractEvent<
      ValueStoredEvent.InputTuple,
      ValueStoredEvent.OutputTuple,
      ValueStoredEvent.OutputObject
    >;
  };
}
